# Generated by Django 4.2.7 on 2026-02-05 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_id', models.IntegerField(unique=True)),
                ('context_prompt', models.TextField(help_text='Context prompt for the lesson')),
                ('common_questions', models.JSONField(default=list, help_text='Common questions and answers')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Контекст чата',
                'verbose_name_plural': 'Контексты чата',
                'db_table': 'chat_contexts',
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('message', models.TextField()),
                ('response', models.TextField()),
                ('lesson_id', models.IntegerField(blank=True, help_text='Context lesson ID', null=True)),
                ('context_data', models.JSONField(default=dict, help_text='Additional context data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Сообщение чата',
                'verbose_name_plural': 'Сообщения чата',
                'db_table': 'chat_messages',
                'indexes': [models.Index(fields=['user_id', 'created_at'], name='chat_messag_user_id_ecc172_idx'), models.Index(fields=['lesson_id'], name='chat_messag_lesson__397165_idx')],
            },
        ),
    ]
